### PR TITLE
[#XGB-151] Add sections on multiple users and audit trail

### PR DESCRIPTION
**Pull request by fabianhauser**

### CODE REVIEW

**Comment by raphiz** [comment]
@fabianhauser thanks, while reading it i wondered why stanza needs the jid...and skimming through the standards, i did not found any reasonable answers as well..so i tried to get rid of if...and it worked :tada: have a look [here](https://github.com/xmpp-grid-broker/xmpp-grid-broker/tree/XGB-151-multiple-users)
Do you agree or did i miss something?

**Comment by fabianhauser** [comment]
@raphiz as discussed, I'm surprised that this works, as I'm sure to have tried that before.
But it looks great, so I think we should implement that this way 😄

**Comment by fabianhauser** [comment]
@raphiz please take a look at the updated version 🙂

**Comment by fabianhauser** [comment]
Thanks for the feedback @raphiz, I addressed it in e663f2a9affec1be10c307ac0ca4fe7e3086a883. Please take a look if you find it easier to read and complete now 🙂

**Comment by raphiz** [comment]
That's great, thanks!

**Pull request merged**
