### PR TITLE
Architectural Decision: Web Application

### PR DESCRIPTION
**Pull request by raphiz**
Did I miss anything :see_no_evil: ?

### CODE REVIEW

**Comment by fabianhauser** [comment]
@raphiz I think most points are covered, however two things are missing:
- Security aspects (if client on desktop, direct XMPP server access?; browser security?)
- Web application needs hosting etc. (and also: Scalability?)

**Comment by raphiz** [comment]
@fabianhauser agreed - not sure if you saw the updated version (i forgot to save before i commited :see_no_evil: 
Concerning the Security aspects: I thought about that but i can not really think of any real security-disadvantage in the browser..

**Comment by fabianhauser** [comment]
@raphiz I did see the new version now; I think my comment still holds 😄

About the Browser security: If the browser is used for other things than accessing this application also, they might pose a greater risk (XSRF etc.; also if we look out for them, we might make mistakes.)

**Comment by raphiz** [comment]
I implemented the changes as discused on the :phone:

**Comment by fabianhauser** [comment]
Thanks @raphiz! :)

**Pull request merged**
