### PR TITLE
Finalise User Stories

### PR DESCRIPTION
**Pull request by raphiz**

### CODE REVIEW

**Comment by fabianhauser** [comment]
I changes some minor language things and added a story for the inspection of persisted items

**Comment by raphiz** [comment]
@fabianhauser Thanks for the review! I think you forgot to commit :wink:  I used `node` by accident and will  fix it after you push you changes :+1:

**Comment by fabianhauser** [comment]
@raphiz you are right, I did not push the changes 🙈
Here they are!

**Comment by raphiz** [comment]
@fabianhauser ok, fixed it. Ready to be merged :+1:

**Comment by fabianhauser** [comment]
@raphiz 👍

**Pull request merged**
