### PR TITLE
Add architectural-decisions template

### PR DESCRIPTION
**Pull request by raphiz**

### CODE REVIEW

**Comment by fabianhauser** [comment]
Or did I misunderstand the purpose of this pull request and you only added the template to the development guide and planned to use the content separately? 🙈😄

**Comment by raphiz** [comment]
:smile: well i guess this is open for discussion - I don't have a strong opinion on that...will fix it right away...

**Comment by raphiz** [comment]
@fabianhauser done :wink:

**Comment by fabianhauser** [comment]
Thanks @raphiz! 😉👍

**Pull request merged**
